name: Check packages and deploy website

env:
  NODE_ENV: production
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  FILE_ID: zHeGLN45wIgf39kqdvKpoj

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/deploy.yml
      - packages/**
  pull_request:
    paths:
      - .github/workflows/deploy.yml
      - packages/**

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: ğŸ‘€ Checkout
        uses: actions/checkout@v4
      - name: â¬¢ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: ğŸ§¶ Yarn install
        run: yarn install --immutable
      - name: ğŸš¨ Lint code
        run: yarn lint --max-warnings 0
      - name: ğŸ“¦ï¸ Build packages
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
        run: yarn build
      - name: â¬‡ï¸ Pull environment information
        run: npx vercel@latest pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }} --cwd=./packages/example-web
      - name: ğŸ“¦ï¸ Build project artifacts
        run: npx vercel@latest build --token=${{ secrets.VERCEL_TOKEN }} --cwd=./packages/example-web
      - name: ğŸš€ Deploy preview website
        if: github.ref != 'refs/heads/main'
        run: npx vercel@latest deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --cwd=./packages/example-web
      - name: ğŸš€ Deploy production website
        if: github.ref == 'refs/heads/main'
        run: npx vercel@latest deploy --prod --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --cwd=./packages/example-web
